#:schema https://panache.bz/panache.schema.json

flavor = "quarto"

[format]
line-width = 100
wrap = "preserve"

[formatters]
ojs = "observable-prettier"
javascript = "biome"
json = "biome"

[formatters.biome]
cmd = "./scripts/format/node_modules/.bin/biome"

[formatters.observable-prettier]
cmd = "bun"
args = ["scripts/format/format-ojs.ts"]
stdin = true
