---
title: "Adaptation Atlas Notebooks"
---

This page will likely note be public facing in production. We have the [landing page](https://adaptationatlas.cgiar.org) for that.
However, this index page is useful in development to bounce between the examples, different notebooks being worked on, etc. 

# Deprecated/Demo Notebooks

These notebooks are example ports from the original Atlas [notebooks](https://observablehq.com/@adaptationatlas).
These may be useful for reference, but are not maintained or updated. 
They may also be useful as examples for how to create your own quarto notebooks, note that some of 'notebook standards' have been added and changed since this point.

- [Analyze Women's Exposure To Climate Hazards](/notebooks/deprecated/gender.qmd)
- [Discover Solutions](/notebooks/deprecated/DiscoverSolutions.qmd)

# Notebook Template
We provide a basic notebook template which can be copied and modified to assist in the development of new notebooks.
This template creates the basic structure for the notebooks as well as loads in some of the useful 
libraries and shared data (such as the admin boundaries).

**Find the template [here](/notebooks/nb_template/notebook_template.qmd)**